#!/bin/bash
#
# Build AppWrangler.app with only the Xcode Command Line Tools (no Xcode needed).
#
#   ./build.sh              release build for Apple Silicon (arm64), ad-hoc signed
#   ./build.sh --universal  arm64 + x86_64
#   ./build.sh --debug      debug build (enables the screenshot/debug hooks)
#   ./build.sh --install    also copy to /Applications
#   ./build.sh --cli        also link `appwrangler` into /opt/homebrew/bin or /usr/local/bin
#   ./build.sh --run        also launch it
#   ./build.sh --zip        also write build/AppWrangler-<version>.zip (for a GitHub release)
#
# Distribution (needs a paid Apple Developer account):
#   SIGN_IDENTITY="Developer ID Application: Your Name (TEAMID)" \
#   NOTARY_PROFILE=appwrangler ./build.sh --notarize
# where the profile was stored once with:
#   xcrun notarytool store-credentials appwrangler --apple-id you@example.com --team-id TEAMID
#
set -euo pipefail
cd "$(dirname "$0")"

VERSION="${VERSION:-1.3.0}"	# release CI passes the tag
# Dotted, so each part fits in 32 bits: WidgetKit rejects a widget whose
# CFBundleVersion LaunchServices can't store ("Bundle version did not match").
BUILD_NUMBER="$(date +%Y%m%d.%H%M)"
LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister
ARCHS=(--arch arm64)
WIDGET_ARCHS=(arm64)
CONFIG=release
INSTALL=0 RUN=0 CLI=0 NOTARIZE=0 ZIP=0
for arg in "$@"; do
	case "$arg" in
		--universal) ARCHS=(--arch arm64 --arch x86_64); WIDGET_ARCHS=(arm64 x86_64) ;;
		--debug) CONFIG=debug ;;
		--install) INSTALL=1 ;;
		--cli) CLI=1 ;;
		--run) RUN=1 ;;
		--notarize) NOTARIZE=1 ;;
		--zip) ZIP=1 ;;
		*) echo "unknown option: $arg" >&2; exit 2 ;;
	esac
done

if ! xcrun --find swift >/dev/null 2>&1; then
	echo "Swift toolchain not found. Install the Command Line Tools: xcode-select --install" >&2
	exit 1
fi

echo "==> Compiling ($CONFIG, ${ARCHS[*]})"
swift build -c "$CONFIG" "${ARCHS[@]}" 2>&1 | grep -v "ld: warning: search path" || true
BIN="$(swift build -c "$CONFIG" "${ARCHS[@]}" --show-bin-path)/AppWrangler"
[ -x "$BIN" ] || { echo "build failed" >&2; exit 1; }

APP="build/AppWrangler.app"
echo "==> Assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/AppWrangler"
cp "$(dirname "$BIN")/AppWranglerWatchdog" "$APP/Contents/MacOS/AppWranglerWatchdog"
sed -e "s/__VERSION__/$VERSION/" -e "s/__BUILD__/$BUILD_NUMBER/" Resources/Info.plist > "$APP/Contents/Info.plist"
cp Resources/status_icon.png Resources/status_icon@2x.png "$APP/Contents/Resources/"
for lproj in Resources/*.lproj; do
	cp -R "$lproj" "$APP/Contents/Resources/"
done
mkdir -p "$APP/Contents/Resources/en.lproj"	# English = the keys themselves
# In-app Help shows the same Markdown docs as GitHub.
mkdir -p "$APP/Contents/Resources/Help"
cp docs/*.md "$APP/Contents/Resources/Help/"
cp -R docs/images "$APP/Contents/Resources/Help/"

# The desktop / Notification Center widget: a WidgetKit extension built with
# plain swiftc. It only reads the status file the app writes (WidgetSnapshot.swift
# is compiled into both).
echo "==> Building the widget"
WIDGET="$APP/Contents/PlugIns/AppWranglerWidget.appex"
mkdir -p "$WIDGET/Contents/MacOS" "$WIDGET/Contents/Resources" build/widget
WOPT=-O; [ "$CONFIG" = debug ] && WOPT=-Onone
WBINS=()
for arch in "${WIDGET_ARCHS[@]}"; do
	# Like Xcode, start in NSExtensionMain: with the Swift `main` as the entry
	# point the extension runtime traps ("Incorrect actor executor assumption").
	swiftc -parse-as-library -application-extension -target "$arch-apple-macos14.0" "$WOPT" -module-name AppWranglerWidget \
		-Xlinker -e -Xlinker _NSExtensionMain \
		Widget/*.swift Sources/AppWranglerKit/WidgetSnapshot.swift -o "build/widget/AppWranglerWidget-$arch"
	WBINS+=("build/widget/AppWranglerWidget-$arch")
done
lipo -create "${WBINS[@]}" -output "$WIDGET/Contents/MacOS/AppWranglerWidget"
sed -e "s/__VERSION__/$VERSION/" -e "s/__BUILD__/$BUILD_NUMBER/" Resources/Widget-Info.plist > "$WIDGET/Contents/Info.plist"
for lproj in Resources/*.lproj; do cp -R "$lproj" "$WIDGET/Contents/Resources/"; done
mkdir -p "$WIDGET/Contents/Resources/en.lproj"

# Icons are generated by scripts/make-icons.swift (re-run it to change the artwork).
iconutil -c icns Resources/AppIcon.iconset -o "$APP/Contents/Resources/AppIcon.icns"

if [ -n "${SIGN_IDENTITY:-}" ]; then
	echo "==> Signing with $SIGN_IDENTITY (hardened runtime)"
	codesign --force --options runtime --timestamp --sign "$SIGN_IDENTITY" "$APP/Contents/MacOS/AppWranglerWatchdog"
	codesign --force --options runtime --timestamp --sign "$SIGN_IDENTITY" \
		--entitlements Resources/Widget.entitlements "$WIDGET"
	codesign --force --options runtime --timestamp --sign "$SIGN_IDENTITY" \
		--entitlements Resources/AppWrangler.entitlements "$APP"
else
	echo "==> Signing (ad-hoc — runs on this Mac; set SIGN_IDENTITY to distribute)"
	codesign --force --sign - --timestamp=none "$APP/Contents/MacOS/AppWranglerWatchdog"
	codesign --force --sign - --entitlements Resources/Widget.entitlements --timestamp=none "$WIDGET"
	codesign --force --sign - --entitlements Resources/AppWrangler.entitlements --timestamp=none "$APP"
fi
codesign --verify --strict "$APP"
echo "==> Built $APP ($(lipo -archs "$APP/Contents/MacOS/AppWrangler"))"

if [ "$NOTARIZE" = 1 ]; then
	[ -n "${SIGN_IDENTITY:-}" ] && [ -n "${NOTARY_PROFILE:-}" ] || { echo "--notarize needs SIGN_IDENTITY and NOTARY_PROFILE" >&2; exit 1; }
	ZIP="build/AppWrangler-$VERSION.zip"
	ditto -c -k --keepParent "$APP" "$ZIP"
	echo "==> Notarizing (this can take a few minutes)"
	xcrun notarytool submit "$ZIP" --keychain-profile "$NOTARY_PROFILE" --wait
	xcrun stapler staple "$APP"
	ditto -c -k --keepParent "$APP" "$ZIP"
	echo "==> Notarized: $ZIP"
fi

if [ "$ZIP" = 1 ] && [ "$NOTARIZE" = 0 ]; then
	ditto -c -k --keepParent "$APP" "build/AppWrangler-$VERSION.zip"
	echo "==> Wrote build/AppWrangler-$VERSION.zip"
fi

if [ "$INSTALL" = 1 ]; then
	pkill -x AppWrangler 2>/dev/null && sleep 1 || true
	pkill -x AppWranglerWidget 2>/dev/null || true	# an old widget process would keep serving the old build
	rm -rf /Applications/AppWrangler.app
	cp -R "$APP" /Applications/
	APP="/Applications/AppWrangler.app"
	# One registered copy only, so the widget gallery and WidgetKit use this one.
	"$LSREGISTER" -u "$PWD/build/AppWrangler.app" 2>/dev/null || true
	"$LSREGISTER" -f -R -trusted "$APP" 2>/dev/null || true
	echo "==> Installed to $APP"
fi

if [ "$CLI" = 1 ]; then
	TARGET="$(cd "$(dirname "$APP")" && pwd)/$(basename "$APP")/Contents/MacOS/AppWrangler"
	for dir in /opt/homebrew/bin /usr/local/bin "$HOME/.local/bin"; do
		if [ -d "$dir" ] && [ -w "$dir" ]; then
			ln -sf "$TARGET" "$dir/appwrangler"
			echo "==> Linked $dir/appwrangler -> $TARGET"
			break
		fi
	done
fi

if [ "$RUN" = 1 ]; then
	pkill -x AppWrangler 2>/dev/null && sleep 1 || true
	open "$APP"
fi
