#!/bin/bash
#
# Build AppWrangler.app with only the Xcode Command Line Tools (no Xcode needed).
#
#   ./build.sh              release build for Apple Silicon (arm64), ad-hoc signed
#   ./build.sh --universal  arm64 + x86_64
#   ./build.sh --debug      debug build (enables the screenshot/debug hooks)
#   ./build.sh --install    also copy to /Applications
#   ./build.sh --cli        also link `appwrangler` into /opt/homebrew/bin or /usr/local/bin
#   ./build.sh --run        also launch it
#   ./build.sh --zip        also write build/AppWrangler-<version>.zip (for a GitHub release)
#
# Distribution (needs a paid Apple Developer account):
#   SIGN_IDENTITY="Developer ID Application: Your Name (TEAMID)" \
#   NOTARY_PROFILE=appwrangler ./build.sh --notarize
# where the profile was stored once with:
#   xcrun notarytool store-credentials appwrangler --apple-id you@example.com --team-id TEAMID
#
set -euo pipefail
cd "$(dirname "$0")"

VERSION="${VERSION:-1.0.0}"	# release CI passes the tag
BUILD_NUMBER="$(date +%Y%m%d%H%M)"
ARCHS=(--arch arm64)
CONFIG=release
INSTALL=0 RUN=0 CLI=0 NOTARIZE=0 ZIP=0
for arg in "$@"; do
	case "$arg" in
		--universal) ARCHS=(--arch arm64 --arch x86_64) ;;
		--debug) CONFIG=debug ;;
		--install) INSTALL=1 ;;
		--cli) CLI=1 ;;
		--run) RUN=1 ;;
		--notarize) NOTARIZE=1 ;;
		--zip) ZIP=1 ;;
		*) echo "unknown option: $arg" >&2; exit 2 ;;
	esac
done

if ! xcrun --find swift >/dev/null 2>&1; then
	echo "Swift toolchain not found. Install the Command Line Tools: xcode-select --install" >&2
	exit 1
fi

echo "==> Compiling ($CONFIG, ${ARCHS[*]})"
swift build -c "$CONFIG" "${ARCHS[@]}" 2>&1 | grep -v "ld: warning: search path" || true
BIN="$(swift build -c "$CONFIG" "${ARCHS[@]}" --show-bin-path)/AppWrangler"
[ -x "$BIN" ] || { echo "build failed" >&2; exit 1; }

APP="build/AppWrangler.app"
echo "==> Assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/AppWrangler"
sed -e "s/__VERSION__/$VERSION/" -e "s/__BUILD__/$BUILD_NUMBER/" Resources/Info.plist > "$APP/Contents/Info.plist"
cp Resources/status_icon.png Resources/status_icon@2x.png "$APP/Contents/Resources/"
for lproj in Resources/*.lproj; do
	cp -R "$lproj" "$APP/Contents/Resources/"
done
mkdir -p "$APP/Contents/Resources/en.lproj"	# English = the keys themselves
# In-app Help shows the same Markdown docs as GitHub.
mkdir -p "$APP/Contents/Resources/Help"
cp docs/*.md "$APP/Contents/Resources/Help/"

# Icons are generated by scripts/make-icons.swift (re-run it to change the artwork).
iconutil -c icns Resources/AppIcon.iconset -o "$APP/Contents/Resources/AppIcon.icns"

if [ -n "${SIGN_IDENTITY:-}" ]; then
	echo "==> Signing with $SIGN_IDENTITY (hardened runtime)"
	codesign --force --options runtime --timestamp --sign "$SIGN_IDENTITY" \
		--entitlements Resources/AppWrangler.entitlements "$APP"
else
	echo "==> Signing (ad-hoc — runs on this Mac; set SIGN_IDENTITY to distribute)"
	codesign --force --sign - --entitlements Resources/AppWrangler.entitlements --timestamp=none "$APP"
fi
codesign --verify --strict "$APP"
echo "==> Built $APP ($(lipo -archs "$APP/Contents/MacOS/AppWrangler"))"

if [ "$NOTARIZE" = 1 ]; then
	[ -n "${SIGN_IDENTITY:-}" ] && [ -n "${NOTARY_PROFILE:-}" ] || { echo "--notarize needs SIGN_IDENTITY and NOTARY_PROFILE" >&2; exit 1; }
	ZIP="build/AppWrangler-$VERSION.zip"
	ditto -c -k --keepParent "$APP" "$ZIP"
	echo "==> Notarizing (this can take a few minutes)"
	xcrun notarytool submit "$ZIP" --keychain-profile "$NOTARY_PROFILE" --wait
	xcrun stapler staple "$APP"
	ditto -c -k --keepParent "$APP" "$ZIP"
	echo "==> Notarized: $ZIP"
fi

if [ "$ZIP" = 1 ] && [ "$NOTARIZE" = 0 ]; then
	ditto -c -k --keepParent "$APP" "build/AppWrangler-$VERSION.zip"
	echo "==> Wrote build/AppWrangler-$VERSION.zip"
fi

if [ "$INSTALL" = 1 ]; then
	pkill -x AppWrangler 2>/dev/null && sleep 1 || true
	rm -rf /Applications/AppWrangler.app
	cp -R "$APP" /Applications/
	APP="/Applications/AppWrangler.app"
	echo "==> Installed to $APP"
fi

if [ "$CLI" = 1 ]; then
	TARGET="$(cd "$(dirname "$APP")" && pwd)/$(basename "$APP")/Contents/MacOS/AppWrangler"
	for dir in /opt/homebrew/bin /usr/local/bin "$HOME/.local/bin"; do
		if [ -d "$dir" ] && [ -w "$dir" ]; then
			ln -sf "$TARGET" "$dir/appwrangler"
			echo "==> Linked $dir/appwrangler -> $TARGET"
			break
		fi
	done
fi

if [ "$RUN" = 1 ]; then
	pkill -x AppWrangler 2>/dev/null && sleep 1 || true
	open "$APP"
fi
