#!/usr/bin/env python3
# Builds the GitHub wiki from the repository's own docs, so there is one source
# of truth (docs/ also ships inside the app as its Help).
#
#   scripts/sync-wiki.py              build into build/wiki and check every link
#   scripts/sync-wiki.py --push       also push the result to the wiki repository
#
# Links between pages are rewritten to wiki page names, images are copied to
# images/, and links to other repository files point at GitHub. Pages carry a
# marker comment, so pages made by hand in the wiki are never touched, while
# generated pages that no longer have a source are removed.
#
# Pushing uses WIKI_TOKEN (CI) or the gh CLI's IntarsO login, and commits as
# IntarsO. The wiki repository only exists after its first page has been
# created in the browser (Wiki tab -> Create the first page -> Save).
import argparse, os, re, shutil, subprocess, sys, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPO = "IntarsO/AppWrangler"
SITE = f"https://github.com/{REPO}"
BLOB, TREE = f"{SITE}/blob/main/", f"{SITE}/tree/main/"
MARK = "<!-- generated by scripts/sync-wiki.py"

# (source file, wiki page, sidebar label)
PAGES = [
    ("README.md", "Home", "Home"),
    ("docs/getting-started.md", "Getting-Started", "Getting started"),
    ("docs/user-manual.md", "User-Manual", "User manual"),
    ("docs/faq.md", "FAQ", "FAQ"),
    ("docs/cli.md", "Command-line", "Command line"),
    ("docs/mcp.md", "MCP", "Use with AI assistants (MCP)"),
    ("docs/how-it-works.md", "How-it-works", "How it works"),
    ("CHANGELOG.md", "Changelog", "Changelog"),
    ("CONTRIBUTING.md", "Contributing", "Contributing"),
]
PAGE_OF = {src: page for src, page, _ in PAGES}

MD_LINK = re.compile(r'(\]\()([^)\s]+)((?:\s+"[^"]*")?\))')
# A link whose text is a file name ([CONTRIBUTING.md](Contributing)) reads better as the page title.
FILE_TEXT = re.compile(r"\[((?:[\w.-]+/)*[\w.-]+\.md)\]\(([A-Za-z-]+)(#[^)\s]*)?\)")
LABEL = {page: label for _, page, label in PAGES}
HTML_ATTR = re.compile(r'\b(href|src)="([^"]+)"')


def rewrite_target(target, source, errors):
    if re.match(r"^[A-Za-z][A-Za-z0-9+.-]*:", target) or target.startswith("#"):
        return target
    path, _, anchor = target.partition("#")
    tail = "#" + anchor if anchor else ""
    resolved = (ROOT / source).parent.joinpath(path).resolve()
    try:
        rel = resolved.relative_to(ROOT).as_posix()
    except ValueError:
        errors.append(f"{source}: link leaves the repository: {target}")
        return target
    if rel in PAGE_OF:
        return PAGE_OF[rel] + tail
    if rel.startswith("docs/images/"):
        return "images/" + rel[len("docs/images/"):]
    if resolved.is_dir():
        return TREE + rel
    if resolved.exists():
        return BLOB + rel + tail
    errors.append(f"{source}: broken link: {target}")
    return target


def convert(text, source, errors):
    out, fenced = [], False
    for line in text.split("\n"):
        if line.lstrip().startswith(("```", "~~~")):
            fenced = not fenced
        elif not fenced:
            line = MD_LINK.sub(lambda m: m.group(1) + rewrite_target(m.group(2), source, errors) + m.group(3), line)
            line = FILE_TEXT.sub(lambda m: f"[{LABEL[m.group(2)]}]({m.group(2)}{m.group(3) or ''})" if m.group(2) in LABEL else m.group(0), line)
            line = HTML_ATTR.sub(lambda m: f'{m.group(1)}="{rewrite_target(m.group(2), source, errors)}"', line)
        out.append(line)
    return "\n".join(out)


def sidebar():
    label = {page: name for _, page, name in PAGES}
    def link(page):
        return f"- [{label[page]}]({page})"
    return "\n".join([
        MARK + " -->",
        "**[AppWrangler](Home)**", "",
        "**Use it**", link("Getting-Started"), link("User-Manual"), link("FAQ"), "",
        "**Go further**", link("Command-line"), link("MCP"), link("How-it-works"), "",
        "**Project**", link("Changelog"), link("Contributing"),
        f"- [Releases]({SITE}/releases/latest)",
        f"- [Discussions]({SITE}/discussions)",
        f"- [Report a bug]({SITE}/issues/new)", "",
    ])


def footer():
    return (MARK + " -->\n"
            f"These pages are generated from the [docs in the repository]({TREE}docs). "
            f"To change one, edit it there and send a pull request; edits made here are overwritten. "
            f"AppWrangler is free software under the [GPL-2.0]({BLOB}LICENSE).\n")


def build(out):
    errors = []
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    for source, page, _ in PAGES:
        text = (ROOT / source).read_text(encoding="utf-8")
        (out / f"{page}.md").write_text(f"{MARK} from {source} -->\n" + convert(text, source, errors), encoding="utf-8")
    (out / "_Sidebar.md").write_text(sidebar(), encoding="utf-8")
    (out / "_Footer.md").write_text(footer(), encoding="utf-8")
    shutil.copytree(ROOT / "docs" / "images", out / "images")
    # Every link in the result must lead somewhere.
    pages = {p.stem for p in out.glob("*.md")}
    for md in sorted(out.glob("*.md")):
        for match in MD_LINK.finditer(md.read_text(encoding="utf-8")):
            target = match.group(2).split("#")[0]
            if not target or re.match(r"^[A-Za-z][A-Za-z0-9+.-]*:", target):
                continue
            if target not in pages and not (out / target).exists():
                errors.append(f"{md.name}: dangling link: {match.group(2)}")
    return errors


def git(args, cwd, env=None):
    return subprocess.run(["git", *args], cwd=cwd, env=env, text=True, capture_output=True)


def push(out):
    token = os.environ.get("WIKI_TOKEN")
    user = "x-access-token"
    if not token:
        user = "IntarsO"
        token = subprocess.run(["gh", "auth", "token", "-u", "IntarsO"], text=True, capture_output=True).stdout.strip()
    if not token:
        sys.exit("No token: set WIKI_TOKEN, or log in to gh as IntarsO.")
    env = dict(os.environ, WIKI_PUSH_TOKEN=token, GIT_TERMINAL_PROMPT="0")
    helper = f"!f() {{ echo username={user}; echo password=$WIKI_PUSH_TOKEN; }}; f"
    auth = ["-c", "credential.helper=", "-c", f"credential.helper={helper}"]
    work = Path(tempfile.mkdtemp(prefix="appwrangler-wiki-"))
    clone = git([*auth, "clone", "-q", f"{SITE}.wiki.git", str(work / "wiki")], None, env)
    if clone.returncode != 0:
        sys.exit("Couldn't clone the wiki. If this is the first time, create its first page once in the browser\n"
                 f"({SITE}/wiki -> Create the first page -> Save), then run this again.\n{clone.stderr.strip()}")
    wiki = work / "wiki"
    keep = {p.name for p in out.glob("*.md")}
    for old in wiki.glob("*.md"):    # generated pages whose source is gone
        if old.name not in keep and MARK in old.read_text(encoding="utf-8", errors="ignore")[:200]:
            old.unlink()
    shutil.rmtree(wiki / "images", ignore_errors=True)
    for item in out.iterdir():
        target = wiki / item.name
        shutil.copytree(item, target) if item.is_dir() else shutil.copy2(item, target)
    git(["add", "-A"], wiki)
    if not git(["status", "--porcelain"], wiki).stdout.strip():
        print("The wiki is already up to date.")
        return
    sha = os.environ.get("GITHUB_SHA") or git(["rev-parse", "HEAD"], ROOT).stdout.strip()
    ident = ["-c", "user.name=IntarsO", "-c", "user.email=30525407+IntarsO@users.noreply.github.com"]
    commit = git([*ident, "commit", "-q", "-m", f"Sync from the repository at {sha[:7]}"], wiki)
    if commit.returncode != 0:
        sys.exit(commit.stderr)
    result = git([*auth, "push", "-q", "origin", "HEAD"], wiki, env)
    if result.returncode != 0:
        sys.exit(f"Push failed:\n{result.stderr}")
    print(f"Pushed to {SITE}/wiki")


def main():
    parser = argparse.ArgumentParser(description="Build (and optionally push) the GitHub wiki from docs/.")
    parser.add_argument("--out", default=str(ROOT / "build" / "wiki"), help="where to build the pages")
    parser.add_argument("--push", action="store_true", help="push the result to the wiki repository")
    args = parser.parse_args()
    out = Path(args.out)
    errors = build(out)
    if errors:
        print("\n".join(errors), file=sys.stderr)
        sys.exit(1)
    print(f"Built {len(PAGES)} pages (+ sidebar, footer, images) in {out}")
    if args.push:
        push(out)


if __name__ == "__main__":
    main()
